feat: conversion of html generated by html-webpack-plugin
originjs/webpack-to-vite pull request #88
Opened 2022-01-28 06:43 UTC by konpeki622

Related to #83 

### transform functional webpack config with AST
  - The `webpackConfigure` and `chainWebpack` options could be defined as object or function in `vue.config.js` module
  - To avoid calling error when they were functional, I initialize config options and generate a temporary file (`vue.temp.config.js`) to reconfig `html-webpack-plugin`

### `html-webpack-plugin` is supported
  - Options will be applied to plugin `vite-plugin-html`
  - Variables injected to `index.html` will be transformed. for example, `<%= htmlWebpackPlugin.options.title %>` -> `<%= title %>`
  - Import `injectHtml` and `minifyHtml` from `html-webpack-plugin`

support these options:

- [x] title
- [x] template
- [x] favicon
- [x] minify
- [x] publicPath
- [x] templateContent
- [x] templateParameter

***
I will add test use cases.

2022-02-12 08:29 UTC, Chieffo2021 requested changes

2022-02-12 08:29 UTC, Chieffo2021 commented on src/ast-parse/astParse.ts
> +          webpackConfig = applyAstParsingResultToConfig(webpackConfig, 'FindWebpackConfigProperties', parsingResults)
Whether `FindWebpackConfigProperties` can be imported from `constants` file.

2022-02-12 08:29 UTC, Chieffo2021 commented on src/transform/transformVuecli.ts
> +          webpackConfig = applyAstParsingResultToConfig(webpackConfig, 'FindWebpackConfigProperties', astParsingResult.parsingResult)
Whether `FindWebpackConfigProperties` can be imported from `constants` file.

2022-02-14 04:07 UTC, konpeki622 commented on src/ast-parse/transformations/chainWebpackTransformation.ts
> +  const extension: string = (/\.([^.]*)$/.exec(fileInfo.path) || [])[0]
That is uncorrect when the extension was longer than 1.

2022-02-14 12:37 UTC, konpeki622 commented on src/utils/astUtils.ts
> +export function parseIdentifierFromBodyNodes (bodyNodes: any[], paramName: string): ParsingResultProperty[][] {
I added comment to this function. It's a little hard to test.

2022-02-17 06:28 UTC, Chieffo2021 commented
Now we have 22 automatic conversions
https://github.com/originjs/webpack-to-vite/blob/fa9a79ace9bcf938bb5c7e32d0d05b6fcaf2663f/src/cli/cli.ts#L50

2022-02-17 06:30 UTC, Chieffo2021 commented on src/ast-parse/astParse.ts
> -  cliInstance.setTotal(cliInstance.total + resolvedPaths.length)
We should not delete this line, the total should be plus the number of ast parsing times the number of files.

2022-02-17 09:00 UTC, Chieffo2021 approved these changes

2022-02-17 09:01 UTC, merged